[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
